"""
Global pygame config for Xiangqi Arena.
"""

# Window
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 820
WINDOW_TITLE = "Xiangqi Arena Demo"

FPS = 60

# Board layout
BOARD_ORIGIN_X = 80
BOARD_ORIGIN_Y = 60
GRID_SIZE = 70

BOARD_COLS = 9
BOARD_ROWS = 10

# Piece drawing
PIECE_RADIUS = 24
PIECE_BORDER_WIDTH = 2
SELECTED_RING_WIDTH = 4

# Marker sizes
MOVE_MARK_RADIUS = 10
ATTACK_MARK_RADIUS = 14
EVENT_MARK_RADIUS = 10

# Side panel
PANEL_X = 760
PANEL_Y = 60
PANEL_WIDTH = 360
PANEL_HEIGHT = 680

# Font
FONT_NAME = None
FONT_SIZE_SMALL = 20
FONT_SIZE_MEDIUM = 28
FONT_SIZE_LARGE = 36